# Generated by Django 4.2.6 on 2023-10-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auctionlisting_listing_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='listing_description',
            field=models.TextField(max_length=5120),
        ),
    ]
