# Generated by Django 4.2.6 on 2023-10-14 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auctionlisting_listing_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='listed_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
