# Generated by Django 4.2.6 on 2023-10-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_auctionlisting_current_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
