# Generated by Django 4.2.6 on 2023-10-16 10:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auctionlisting_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingcomment',
            name='comment_creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
